version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dashbase/night-watch
    docker:
    - image: circleci/golang:1.11

    steps:

    - checkout

    - setup_remote_docker:
        docker_layer_caching: true

#    - restore_cache:
#        keys:
#        - venv-{{ checksum "Pipfile" }}
#
    - run:
        name: Set up environment
        command: |
          curl -fsSL https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 -o github-release.tar.bz2
          tar -jxvf github-release.tar.bz2
          sudo mv bin/linux/amd64/github-release /usr/bin/

    - run:
        name: make
        command: |
          make build_linux

#    - save_cache:
#        key: venv-{{ checksum "Pipfile" }}
#        paths:
#        - "venv"

    - deploy:
        name: "echo"
        command: |
          if [ "${CIRCLE_BRANCH}" == "ci" ]; then
            echo "2"
          fi
    - deploy:
        name: "Push image to Docker Hub"
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build . -t dashbase/dashbase-tools
            docker push dashbase/dashbase-tools
          elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build . -t dashbase/dashbase-tools:dev
            docker push dashbase/dashbase-tools:dev
          elif [ -n "${CIRCLE_TAG}" ]; then
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build . -t dashbase/dashbase-tools:${CIRCLE_TAG:1}
            docker push dashbase/dashbase-tools:${CIRCLE_TAG:1}
          fi
workflows:
  version: 2
  build-n-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/